--- #YAML:1.0
name:                Net-Frame-Simple
version:             1.03
abstract:            frame crafting made easy
license:             artistic
author:              
    - GomoR <perl@gomor.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Class::Gomor:                  1.00
    Net::Frame:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
