--- #YAML:1.0
name:                Net-Frame-Simple
version:             1.01
abstract:            frame crafting made easy
license:             Artistic
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Class::Gomor:                  1.00
    Net::Frame:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - GomoR <perl@gomor.org>
